import type { CommandMeta } from "./types.js";

export const COMMANDS = [
  {
    id: "release-prepare",
    title: "release prepare",
    shortDescription: "Підготовка версії та changelog",
    flowOrder: 1,
    steps: [
      "Перевірки",
      "Генерація changelog",
      "Оновлення версії",
      "Preview",
      "Git контекст",
      "Збереження state",
    ],
    does: "Оновлює версію релізних файлів, готує changelog та формує state для apply.",
    example: "yarn release prepare 0.8.3",
    expectedResult:
      "Оновлені release-файли та збережений .git/release-prepare-state.json.",
  },
  {
    id: "release-apply",
    title: "release apply",
    shortDescription: "Commit, tag і опційний push",
    flowOrder: 2,
    steps: ["Перевірки", "Commit", "Tag", "Push", "Очистка state"],
    does: "Створює commit і tag для релізу, опційно пушить у origin.",
    example: "yarn release apply 0.8.3 --push",
    expectedResult: "Реліз зафіксовано в git, state очищено.",
  },
  {
    id: "release-rollback-prepare",
    title: "release rollback-prepare",
    shortDescription: "Відкат локального prepare",
    flowOrder: 3,
    steps: ["Пошук змін", "Restore", "Очистка state"],
    does: "Відновлює локальні зміни після prepare у whitelist-файлах.",
    example: "yarn release rollback-prepare --yes",
    expectedResult: "Локальні prepare-зміни скасовано.",
  },
  {
    id: "deploy-web",
    title: "deploy-web",
    shortDescription: "Збірка та публікація web",
    flowOrder: 4,
    steps: ["Typecheck", "Build", "Upload", "Switch symlink", "Prune"],
    does: "Збирає web-артефакти і публікує їх на віддалений сервер.",
    example: "yarn deploy:web --mode production",
    expectedResult: "Новий реліз активовано на сервері.",
  },
  {
    id: "build-apk",
    title: "build-apk",
    shortDescription: "Збірка Android APK",
    flowOrder: 5,
    steps: ["Typecheck", "Build", "cap sync", "Gradle", "Archive", "Upload"],
    does: "Збирає debug APK, архівує та опційно завантажує файл.",
    example: "yarn build:apk stable",
    expectedResult: "APK доступний у apk-output/ або в remote upload.",
  },
  {
    id: "rollback",
    title: "rollback",
    shortDescription: "Перемикання на попередній реліз",
    flowOrder: 6,
    steps: ["Вибір target", "Switch symlink"],
    does: "Перемикає активний html symlink на попередній або обраний реліз.",
    example: "yarn rollback 0.8.2",
    expectedResult: "Активовано попередній (або заданий) реліз.",
  },
  {
    id: "bump-version",
    title: "bump-version",
    shortDescription: "Оновлення версії без commit",
    flowOrder: 7,
    steps: ["Оновлення package", "Оновлення gradle"],
    does: "Оновлює версії у release-файлах без git операцій.",
    example: "yarn bump-version 0.8.4 --bump-code",
    expectedResult: "Версійні поля файлів оновлено локально.",
  },
] satisfies CommandMeta[];

COMMANDS.sort((a, b) => a.flowOrder - b.flowOrder);
